version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/" # Root directory for Python dependencies
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    rebase-strategy: "auto" # Automatically resolve merge conflicts
    allow:
      - dependency-type: "direct" # Allow only direct dependencies
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "LuccaVG"
    ignore:
      - dependency-name: "example-library"
        versions: [">=4.0.0,<5.0.0"] # Ignore specific versions of example-library
    milestone: 1 # Associate with milestone 1

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/" # Root directory for GitHub Actions workflows
    schedule:
      interval: "daily"
      time: "07:00"
    commit-message:
      prefix: "actions"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "LuccaVG"

  # Docker updates
  - package-ecosystem: "docker"
    directory: "/" # Root directory for Docker files
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "LuccaVG"

  # Terraform updates
  - package-ecosystem: "terraform"
    directory: "/" # Root directory for Terraform configurations
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "terraform"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "terraform"
    reviewers:
      - "LuccaVG"

  # npm updates
  - package-ecosystem: "npm"
    directory: "/" # Root directory for JavaScript dependencies
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
    commit-message:
      prefix: "npm"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
    reviewers:
      - "LuccaVG"

  # OS package updates (Go modules)
  - package-ecosystem: "gomod"
    directory: "/" # Root directory for Go modules
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "11:00"
    commit-message:
      prefix: "os"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "os"
    reviewers:
      - "LuccaVG"
