version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/" # Adjust if requirements.txt is not in the root directory
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "LuccaVG"

  # Go modules (commented out if not used yet)
  # - package-ecosystem: "gomod"
  #   directory: "/" # Ensure go.mod exists in the root directory
  #   schedule:
  #     interval: "weekly"
  #     day: "tuesday"
  #     time: "09:00"
  #   commit-message:
  #     prefix: "go"
  #   open-pull-requests-limit: 5
  #   labels:
  #     - "dependencies"
  #     - "go"
  #   reviewers:
  #     - "LuccaVG"
