version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/" # Root directory for Python dependencies
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    rebase-strategy: "auto" # Automatically resolve merge conflicts
    allow:
      - dependency-type: "direct" # Allow only direct dependencies
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "LuccaVG"
    ignore:
      - dependency-name: "example-library"
        versions: [">=4.0.0,<5.0.0"] # Ignore specific versions of example-library
    milestone: 1 # Associate with milestone 1
