version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/" # Root directory for Python dependencies
    schedule:
      interval: "weekly" # Check for updates weekly

  # Go modules (gomod)
  - package-ecosystem: "gomod"
    directory: "/" # Root directory for Go dependencies
    schedule:
      interval: "weekly" # Check for updates weekly
